global:
  # Configuración global de SMTP para notificaciones por email
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'matthew.salazar1141@gmail.com'
  smtp_auth_username: 'matthew.salazar1141@gmail.com'
  smtp_auth_password: 'gckbrrwpjwkkmcfv'

# Configuración de rutas
route:
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-alerts'
  routes:
    - match:
        severity: critical
      receiver: critical-alerts
      group_wait: 5s
      repeat_interval: 30m
    - match:    
        severity: warning
      receiver: warning-alerts
      repeat_interval: 2h

# Configuración de receptores
receivers:
  - name: 'default-alerts'
    email_configs:
      - to: 'matthew.salazar1141@gmail.com'
        subject: 'Alerta del Sistema de Préstamos'
        body: 'Se ha activado una alerta en el sistema.'

  - name: 'critical-alerts'
    email_configs:
      - to: 'matthew.salazar1141@gmail.com'
        subject: 'ALERTA CRÍTICA - Sistema de Préstamos'
        body: 'Se ha detectado una alerta crítica en el sistema.'

  - name: 'warning-alerts'
    email_configs:
      - to: 'matthew.salazar1141@gmail.com'
        subject: 'ADVERTENCIA - Sistema de Préstamos'
        body: 'Se ha detectado una advertencia en el sistema.'

# Configuración de inhibición
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']
